new-session -n tmux                                         # attach will create session if absent
#set -g default-terminal "screen-256color"
set -g mouse on                                             # mouse support
set -g base-index 1                                         # Start windows and panes at 1, not 0
setw -g pane-base-index 1                                   # ^
setw -g monitor-activity on                                 # alert on activity
set -g visual-activity on                                   # ^
set-option -g history-limit 20000                           # bigger scrollback buffer x10
set-option -g renumber-windows on                           # auto renumber on delete
set-window-option -g window-status-current-style bg=yellow  # highlight active window in status bar
