# Kerberos
#set-option -g update-environment "DISPLAY SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY KRB5CCNAME

# mouse support
set -g mouse on

# alert on activity
setw -g monitor-activity on
set -g visual-activity on

# highlight active window in status bar
set-window-option -g window-status-current-bg yellow

# 256 colors
set -g default-terminal "screen-256color"

# reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

