# mouse support
set -g mouse on

# bigger scrollback buffer x10
set-option -g history-limit 20000

# auto renumber on delete
set-option -g renumber-windows on

# alert on activity
setw -g monitor-activity on
set -g visual-activity on

# highlight active window in status bar
set-window-option -g window-status-current-bg yellow

# 256 colors
set -g default-terminal "screen-256color"

# reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

