# server options
set-option -sa terminal-features ',*256color:RGB'       # 24bit colors
set-option -sa terminal-features ',*:hyperlinks'        # clicky URLs
# (global) session options
set-option -g base-index 1                              # start windows at 1 (not 0)
set-option -g default-terminal 'tmux-256color'          # force set TERM
set-option -g history-limit 20000                       # bigger scrollback buffer x10
set-option -g mouse on                                  # mouse support
set-option -g renumber-windows on                       # renumber on delete
set-option -g visual-activity on                        # message only (no bell)
# darken non-active panes
set-option -g window-style 'bg=color250'
set-option -g window-active-style 'bg=terminal'
# (global) window options
set-option -gw monitor-activity on                      # highlight status bar on activity
set-option -gw pane-base-index 1                        # start panes at 1 (not 0)
set-option -gw window-status-current-style 'bg=yellow'  # highlight active window in status bar
# plugins
set-option -g @plugin 'tmux-plugins/tpm'
set-option -g @plugin 'tmux-plugins/tmux-resurrect'
set-option -g @plugin 'tmux-plugins/tmux-continuum'
set-option -g @continuum-restore 'on'                   # automatic restore after reboot
if 'test ! -d ~/.config/tmux/plugins/tpm' \
    'run "git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins"'
run '~/.config/tmux/plugins/tpm/tpm'
